### ISSUE TITLE
Translate bitcoin_ja.ts

### ISSUE THREAD

**Issue by kazu0617** [NEETCOINTeam/NEETCOIN#26]
bitcoin_ja.tsの内容について、一部機械翻訳と見受けられるところがあるものについて、上流であるBitCoinを優先するためにあえて変えないか、一部独自で変更するかについて。
一つプルリクを出しましたがここだけでもないのでissueを立てました。
![Test](https://cdn.discordapp.com/attachments/372538720378683392/420448506327728129/unknown.png)

**Comment by ghost** [comment]
NEETCOINはBitcoin Coreの翻訳に追随していません。翻訳の誤り等、何かお気づきの点がありましたらご指摘の程お願い致します。

**Comment by kazu3kazu3** [comment]
Fork元がバリバリの機械翻訳で、いろりろと直しましたが、漏れていたらり新たな誤植作ったところもあります。気づいたところがありましたらご指摘願います。

**Comment by ghost** [comment]
@kazu0617 追加の修正が無ければcloseしてください
